export const registerUser = async (req, res, next) => {
    try {
    } catch (error) {
        next(error)
    }
}

export const loginUser = async (req, res, next) => {
    try {
    } catch (error) {
        next(error)
    }
}
